// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: readyIndicator.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_readyIndicator_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_readyIndicator_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_readyIndicator_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_readyIndicator_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_readyIndicator_2eproto;
namespace readyIndicator {
class readyIndicator;
class readyIndicatorDefaultTypeInternal;
extern readyIndicatorDefaultTypeInternal _readyIndicator_default_instance_;
}  // namespace readyIndicator
PROTOBUF_NAMESPACE_OPEN
template<> ::readyIndicator::readyIndicator* Arena::CreateMaybeMessage<::readyIndicator::readyIndicator>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace readyIndicator {

// ===================================================================

class readyIndicator :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:readyIndicator.readyIndicator) */ {
 public:
  readyIndicator();
  virtual ~readyIndicator();

  readyIndicator(const readyIndicator& from);
  readyIndicator(readyIndicator&& from) noexcept
    : readyIndicator() {
    *this = ::std::move(from);
  }

  inline readyIndicator& operator=(const readyIndicator& from) {
    CopyFrom(from);
    return *this;
  }
  inline readyIndicator& operator=(readyIndicator&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const readyIndicator& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const readyIndicator* internal_default_instance() {
    return reinterpret_cast<const readyIndicator*>(
               &_readyIndicator_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(readyIndicator& a, readyIndicator& b) {
    a.Swap(&b);
  }
  inline void Swap(readyIndicator* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline readyIndicator* New() const final {
    return CreateMaybeMessage<readyIndicator>(nullptr);
  }

  readyIndicator* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<readyIndicator>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const readyIndicator& from);
  void MergeFrom(const readyIndicator& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(readyIndicator* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "readyIndicator.readyIndicator";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_readyIndicator_2eproto);
    return ::descriptor_table_readyIndicator_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSerializedThreadIdFieldNumber = 1,
  };
  // string serialized_thread_id = 1;
  void clear_serialized_thread_id();
  const std::string& serialized_thread_id() const;
  void set_serialized_thread_id(const std::string& value);
  void set_serialized_thread_id(std::string&& value);
  void set_serialized_thread_id(const char* value);
  void set_serialized_thread_id(const char* value, size_t size);
  std::string* mutable_serialized_thread_id();
  std::string* release_serialized_thread_id();
  void set_allocated_serialized_thread_id(std::string* serialized_thread_id);
  private:
  const std::string& _internal_serialized_thread_id() const;
  void _internal_set_serialized_thread_id(const std::string& value);
  std::string* _internal_mutable_serialized_thread_id();
  public:

  // @@protoc_insertion_point(class_scope:readyIndicator.readyIndicator)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr serialized_thread_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_readyIndicator_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// readyIndicator

// string serialized_thread_id = 1;
inline void readyIndicator::clear_serialized_thread_id() {
  serialized_thread_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& readyIndicator::serialized_thread_id() const {
  // @@protoc_insertion_point(field_get:readyIndicator.readyIndicator.serialized_thread_id)
  return _internal_serialized_thread_id();
}
inline void readyIndicator::set_serialized_thread_id(const std::string& value) {
  _internal_set_serialized_thread_id(value);
  // @@protoc_insertion_point(field_set:readyIndicator.readyIndicator.serialized_thread_id)
}
inline std::string* readyIndicator::mutable_serialized_thread_id() {
  // @@protoc_insertion_point(field_mutable:readyIndicator.readyIndicator.serialized_thread_id)
  return _internal_mutable_serialized_thread_id();
}
inline const std::string& readyIndicator::_internal_serialized_thread_id() const {
  return serialized_thread_id_.GetNoArena();
}
inline void readyIndicator::_internal_set_serialized_thread_id(const std::string& value) {
  
  serialized_thread_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void readyIndicator::set_serialized_thread_id(std::string&& value) {
  
  serialized_thread_id_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:readyIndicator.readyIndicator.serialized_thread_id)
}
inline void readyIndicator::set_serialized_thread_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  serialized_thread_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:readyIndicator.readyIndicator.serialized_thread_id)
}
inline void readyIndicator::set_serialized_thread_id(const char* value, size_t size) {
  
  serialized_thread_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:readyIndicator.readyIndicator.serialized_thread_id)
}
inline std::string* readyIndicator::_internal_mutable_serialized_thread_id() {
  
  return serialized_thread_id_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* readyIndicator::release_serialized_thread_id() {
  // @@protoc_insertion_point(field_release:readyIndicator.readyIndicator.serialized_thread_id)
  
  return serialized_thread_id_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void readyIndicator::set_allocated_serialized_thread_id(std::string* serialized_thread_id) {
  if (serialized_thread_id != nullptr) {
    
  } else {
    
  }
  serialized_thread_id_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), serialized_thread_id);
  // @@protoc_insertion_point(field_set_allocated:readyIndicator.readyIndicator.serialized_thread_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace readyIndicator

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_readyIndicator_2eproto
