// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: readyIndicator.proto

#include "readyIndicator.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace readyIndicator {
class readyIndicatorDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<readyIndicator> _instance;
} _readyIndicator_default_instance_;
}  // namespace readyIndicator
static void InitDefaultsscc_info_readyIndicator_readyIndicator_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::readyIndicator::_readyIndicator_default_instance_;
    new (ptr) ::readyIndicator::readyIndicator();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::readyIndicator::readyIndicator::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_readyIndicator_readyIndicator_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_readyIndicator_readyIndicator_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_readyIndicator_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_readyIndicator_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_readyIndicator_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_readyIndicator_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::readyIndicator::readyIndicator, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::readyIndicator::readyIndicator, serialized_thread_id_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::readyIndicator::readyIndicator)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::readyIndicator::_readyIndicator_default_instance_),
};

const char descriptor_table_protodef_readyIndicator_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024readyIndicator.proto\022\016readyIndicator\"."
  "\n\016readyIndicator\022\034\n\024serialized_thread_id"
  "\030\001 \001(\tb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_readyIndicator_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_readyIndicator_2eproto_sccs[1] = {
  &scc_info_readyIndicator_readyIndicator_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_readyIndicator_2eproto_once;
static bool descriptor_table_readyIndicator_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_readyIndicator_2eproto = {
  &descriptor_table_readyIndicator_2eproto_initialized, descriptor_table_protodef_readyIndicator_2eproto, "readyIndicator.proto", 94,
  &descriptor_table_readyIndicator_2eproto_once, descriptor_table_readyIndicator_2eproto_sccs, descriptor_table_readyIndicator_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_readyIndicator_2eproto::offsets,
  file_level_metadata_readyIndicator_2eproto, 1, file_level_enum_descriptors_readyIndicator_2eproto, file_level_service_descriptors_readyIndicator_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_readyIndicator_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_readyIndicator_2eproto), true);
namespace readyIndicator {

// ===================================================================

void readyIndicator::InitAsDefaultInstance() {
}
class readyIndicator::_Internal {
 public:
};

readyIndicator::readyIndicator()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:readyIndicator.readyIndicator)
}
readyIndicator::readyIndicator(const readyIndicator& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  serialized_thread_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_serialized_thread_id().empty()) {
    serialized_thread_id_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.serialized_thread_id_);
  }
  // @@protoc_insertion_point(copy_constructor:readyIndicator.readyIndicator)
}

void readyIndicator::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_readyIndicator_readyIndicator_2eproto.base);
  serialized_thread_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

readyIndicator::~readyIndicator() {
  // @@protoc_insertion_point(destructor:readyIndicator.readyIndicator)
  SharedDtor();
}

void readyIndicator::SharedDtor() {
  serialized_thread_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void readyIndicator::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const readyIndicator& readyIndicator::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_readyIndicator_readyIndicator_2eproto.base);
  return *internal_default_instance();
}


void readyIndicator::Clear() {
// @@protoc_insertion_point(message_clear_start:readyIndicator.readyIndicator)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  serialized_thread_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

const char* readyIndicator::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string serialized_thread_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_serialized_thread_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "readyIndicator.readyIndicator.serialized_thread_id"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* readyIndicator::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:readyIndicator.readyIndicator)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string serialized_thread_id = 1;
  if (this->serialized_thread_id().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_serialized_thread_id().data(), static_cast<int>(this->_internal_serialized_thread_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "readyIndicator.readyIndicator.serialized_thread_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_serialized_thread_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:readyIndicator.readyIndicator)
  return target;
}

size_t readyIndicator::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:readyIndicator.readyIndicator)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string serialized_thread_id = 1;
  if (this->serialized_thread_id().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_serialized_thread_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void readyIndicator::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:readyIndicator.readyIndicator)
  GOOGLE_DCHECK_NE(&from, this);
  const readyIndicator* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<readyIndicator>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:readyIndicator.readyIndicator)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:readyIndicator.readyIndicator)
    MergeFrom(*source);
  }
}

void readyIndicator::MergeFrom(const readyIndicator& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:readyIndicator.readyIndicator)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.serialized_thread_id().size() > 0) {

    serialized_thread_id_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.serialized_thread_id_);
  }
}

void readyIndicator::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:readyIndicator.readyIndicator)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void readyIndicator::CopyFrom(const readyIndicator& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:readyIndicator.readyIndicator)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool readyIndicator::IsInitialized() const {
  return true;
}

void readyIndicator::InternalSwap(readyIndicator* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  serialized_thread_id_.Swap(&other->serialized_thread_id_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::PROTOBUF_NAMESPACE_ID::Metadata readyIndicator::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace readyIndicator
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::readyIndicator::readyIndicator* Arena::CreateMaybeMessage< ::readyIndicator::readyIndicator >(Arena* arena) {
  return Arena::CreateInternal< ::readyIndicator::readyIndicator >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
