// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_weather_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_weather_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_weather_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_weather_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_weather_2eproto;
namespace weather {
class weather;
class weatherDefaultTypeInternal;
extern weatherDefaultTypeInternal _weather_default_instance_;
}  // namespace weather
PROTOBUF_NAMESPACE_OPEN
template<> ::weather::weather* Arena::CreateMaybeMessage<::weather::weather>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace weather {

// ===================================================================

class weather :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:weather.weather) */ {
 public:
  weather();
  virtual ~weather();

  weather(const weather& from);
  weather(weather&& from) noexcept
    : weather() {
    *this = ::std::move(from);
  }

  inline weather& operator=(const weather& from) {
    CopyFrom(from);
    return *this;
  }
  inline weather& operator=(weather&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const weather& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const weather* internal_default_instance() {
    return reinterpret_cast<const weather*>(
               &_weather_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(weather& a, weather& b) {
    a.Swap(&b);
  }
  inline void Swap(weather* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline weather* New() const final {
    return CreateMaybeMessage<weather>(nullptr);
  }

  weather* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<weather>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const weather& from);
  void MergeFrom(const weather& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(weather* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "weather.weather";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_weather_2eproto);
    return ::descriptor_table_weather_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kZipcodeFieldNumber = 1,
    kTemperatureFieldNumber = 2,
    kRelhumidityFieldNumber = 3,
  };
  // int32 zipcode = 1;
  void clear_zipcode();
  ::PROTOBUF_NAMESPACE_ID::int32 zipcode() const;
  void set_zipcode(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_zipcode() const;
  void _internal_set_zipcode(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 temperature = 2;
  void clear_temperature();
  ::PROTOBUF_NAMESPACE_ID::int32 temperature() const;
  void set_temperature(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_temperature() const;
  void _internal_set_temperature(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 relhumidity = 3;
  void clear_relhumidity();
  ::PROTOBUF_NAMESPACE_ID::int32 relhumidity() const;
  void set_relhumidity(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_relhumidity() const;
  void _internal_set_relhumidity(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:weather.weather)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int32 zipcode_;
  ::PROTOBUF_NAMESPACE_ID::int32 temperature_;
  ::PROTOBUF_NAMESPACE_ID::int32 relhumidity_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_weather_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// weather

// int32 zipcode = 1;
inline void weather::clear_zipcode() {
  zipcode_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 weather::_internal_zipcode() const {
  return zipcode_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 weather::zipcode() const {
  // @@protoc_insertion_point(field_get:weather.weather.zipcode)
  return _internal_zipcode();
}
inline void weather::_internal_set_zipcode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  zipcode_ = value;
}
inline void weather::set_zipcode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_zipcode(value);
  // @@protoc_insertion_point(field_set:weather.weather.zipcode)
}

// int32 temperature = 2;
inline void weather::clear_temperature() {
  temperature_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 weather::_internal_temperature() const {
  return temperature_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 weather::temperature() const {
  // @@protoc_insertion_point(field_get:weather.weather.temperature)
  return _internal_temperature();
}
inline void weather::_internal_set_temperature(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  temperature_ = value;
}
inline void weather::set_temperature(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_temperature(value);
  // @@protoc_insertion_point(field_set:weather.weather.temperature)
}

// int32 relhumidity = 3;
inline void weather::clear_relhumidity() {
  relhumidity_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 weather::_internal_relhumidity() const {
  return relhumidity_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 weather::relhumidity() const {
  // @@protoc_insertion_point(field_get:weather.weather.relhumidity)
  return _internal_relhumidity();
}
inline void weather::_internal_set_relhumidity(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  relhumidity_ = value;
}
inline void weather::set_relhumidity(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_relhumidity(value);
  // @@protoc_insertion_point(field_set:weather.weather.relhumidity)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace weather

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_weather_2eproto
